[changelog]
header = """
# Changelog\n
"""
body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.breaking %}[**BREAKING**] {% endif %}{{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^docs?", group = "Documentation" },
  { message = "^perf", group = "Performance" },
  { message = "^deps?", group = "Dependencies" },
  { message = "^refactor", skip = true },
  { message = "^chore", skip = true },
  { message = "^test", skip = true },
  { message = "^style", skip = true },
  { message = "^ci", skip = true },
]
filter_commits = true
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "v0.1.0"
