/**
 * Tier 1 EventReducer (issue #435).
 *
 * Pure function {@code (state, envelope) → newState} that turns the daemon's
 * flat event stream (from the WebSocket bridge, #431) into a hierarchical
 * {@link ExecutionTree}. The reducer is the ONLY place where flat → tree
 * mapping happens — see #439 for why this lives in the frontend rather than
 * the daemon.
 *
 * Architectural rules
 * - Pure: no I/O, no time-dependent helpers (timestamps come from envelopes).
 * - Immutable: every update returns a new state; never mutates inputs.
 * - Forward-compatible: unknown methods are silently ignored so Tier 2/3
 *   additions don't require reducer changes.
 * - Watermark-aware: every dispatch advances {@code state.lastEventId} so
 *   #432's snapshot/reconnect can deduplicate cleanly.
 */

import type {
  DaemonEvent,
  DaemonEventEnvelope,
  PermissionRequestParams,
  PlanCreatedParams,
  PlanStepStartedParams,
  PlanStepCompletedParams,
  PlanStepFallbackParams,
  PlanReplannedParams,
  PlanCompletedParams,
  PlanEscalatedParams,
  SessionEndedParams,
  SessionStartedParams,
  SubAgentEndParams,
  SubAgentStartParams,
  TextDeltaParams,
  ThinkingDeltaParams,
  ToolCompletedParams,
  ToolUseParams,
  TurnCompletedParams,
  TurnStartedParams,
  UsageParams,
  CompactionParams,
} from '../types/events';
import type { ExecutionNode, ExecutionStatus, ExecutionTree } from '../types/tree';

/**
 * The reducer takes only well-typed envelopes. Forward-compatibility for
 * Tier 2/3 events is enforced at the hook layer — the hook validates the
 * inbound method against the {@link DaemonEvent} union and drops anything
 * unknown before dispatch. That keeps the switch below exhaustive in the
 * type system without sprinkling casts through every case body.
 */
type Envelope = DaemonEventEnvelope<DaemonEvent>;

// ---------------------------------------------------------------------------
// ID helpers — single source of truth for synthetic node ids
// ---------------------------------------------------------------------------
//
// These ids are generated by the reducer (the daemon doesn't know about
// frontend node identity), so create-site and lookup-site MUST agree on the
// format. Centralising the format here prevents drift bugs that would
// otherwise be silent — a typo in one place would just no-op the lookup.

/** ID for the synthesised step node under a plan. 1-based to match the wire format. */
export function stepNodeId(planId: string, stepIndex: number): string {
  return `${planId}:step:${stepIndex}`;
}

/**
 * ID for the text bubble of a single ReAct iteration. The previous form
 * keyed text on the turn ({@code `${turnId}:text`}) and rolled every
 * delta the turn ever produced into one node — but a turn typically
 * contains multiple LLM calls, each potentially emitting its own
 * narrative text before tool_use, plus a final response text. Lumping
 * them together produces a single ever-growing "response" node that
 * lives from the very first delta and visually drags as later
 * iterations are added. Keying on the iteration's thinking id instead
 * gives one text node per LLM call, attached to that call's thinking
 * as a sibling of its tools.
 */
export function textNodeId(thinkingId: string): string {
  return `${thinkingId}:text`;
}

/**
 * Fallback id for text emitted in an iteration that produced no
 * thinking event (extended thinking off, or model emitted text first).
 * Keyed on the turn so we still get at most one such node per turn.
 */
export function turnTextNodeId(turnId: string): string {
  return `${turnId}:text:no-thinking`;
}

/** ID for the rolled-up thinking-bubble child of a turn. One per turn. */
export function thinkingNodeId(turnId: string): string {
  return `${turnId}:thinking`;
}

// ---------------------------------------------------------------------------
// Tree helpers (pure, recursive, immutable)
// ---------------------------------------------------------------------------

/** Returns the path from root to {@code id}, or null if not found. */
function findPath(
  nodes: ExecutionNode[],
  id: string,
): ExecutionNode[] | null {
  for (const n of nodes) {
    if (n.id === id) return [n];
    const sub = findPath(n.children, id);
    if (sub) return [n, ...sub];
  }
  return null;
}

/** Returns the matching node anywhere in the tree, or null. */
function findNode(
  nodes: ExecutionNode[],
  id: string,
): ExecutionNode | null {
  for (const n of nodes) {
    if (n.id === id) return n;
    const sub = findNode(n.children, id);
    if (sub) return sub;
  }
  return null;
}

/**
 * Returns the nearest ancestor of {@code fromId} (inclusive) for which
 * {@code predicate} holds, or null. Walks the path root→fromId in reverse so
 * "fromId itself" wins over its parent on a tie.
 */
function findNearestAncestor(
  rootNodes: ExecutionNode[],
  fromId: string | null,
  predicate: (n: ExecutionNode) => boolean,
): ExecutionNode | null {
  if (!fromId) return null;
  const path = findPath(rootNodes, fromId);
  if (!path) return null;
  for (let i = path.length - 1; i >= 0; i--) {
    const candidate = path[i];
    if (candidate && predicate(candidate)) return candidate;
  }
  return null;
}

/**
 * Replaces a node anywhere in the forest by id. Returns a new forest with
 * structural sharing for branches that did not change.
 */
function mapNode(
  nodes: ExecutionNode[],
  id: string,
  updater: (n: ExecutionNode) => ExecutionNode,
): ExecutionNode[] {
  let changed = false;
  const next = nodes.map((n) => {
    if (n.id === id) {
      changed = true;
      return updater(n);
    }
    if (n.children.length === 0) return n;
    const newChildren = mapNode(n.children, id, updater);
    if (newChildren !== n.children) {
      changed = true;
      return { ...n, children: newChildren };
    }
    return n;
  });
  return changed ? next : nodes;
}

/** Appends a child under {@code parentId}. Parent must already exist. */
function appendChild(
  nodes: ExecutionNode[],
  parentId: string,
  child: ExecutionNode,
): ExecutionNode[] {
  return mapNode(nodes, parentId, (parent) => ({
    ...parent,
    children: [...parent.children, child],
  }));
}

/**
 * Finds the natural parent for a new turn or plan: the deepest running step
 * (when a plan is mid-execution), else the deepest session ancestor of the
 * current active node, else any session matching {@code sessionId} at the
 * root, else null. Centralises the three-fallback walk that
 * {@link addTurnNode} and {@link addPlanSkeleton} both need.
 */
function findTurnParent(
  state: ExecutionTree,
  sessionId: string,
): ExecutionNode | null {
  return (
    findNearestAncestor(
      state.rootNodes,
      state.activeNodeId,
      (n) => n.type === 'step' && n.status === 'running',
    ) ??
    findNearestAncestor(
      state.rootNodes,
      state.activeNodeId,
      (n) => n.type === 'session',
    ) ??
    state.rootNodes.find((n) => n.id === sessionId) ??
    null
  );
}

// ---------------------------------------------------------------------------
// Per-method handlers — each returns a new ExecutionTree
// ---------------------------------------------------------------------------

function addSessionNode(
  state: ExecutionTree,
  params: SessionStartedParams,
): ExecutionTree {
  // Idempotent: if the session node already exists (e.g. from a snapshot
  // replay), don't double-add. Compare on type+sessionId rather than node id
  // so we tolerate snapshot shapes that pre-date this dispatch.
  const existing = state.rootNodes.find(
    (n) => n.type === 'session' && n.id === params.sessionId,
  );
  if (existing) return state;

  const node: ExecutionNode = {
    id: params.sessionId,
    type: 'session',
    status: 'running',
    label: `session (${params.model})`,
    startTime: Date.parse(params.timestamp),
    children: [],
    metadata: { model: params.model },
  };
  return {
    ...state,
    rootNodes: [...state.rootNodes, node],
    activeNodeId: node.id,
  };
}

function closeSessionNode(
  state: ExecutionTree,
  params: SessionEndedParams,
): ExecutionTree {
  // No-op when the ended session is not the one this tree is rendering —
  // useExecutionTree's cross-session filter usually catches that, but the
  // reducer is single-session by contract anyway.
  if (params.sessionId !== state.sessionId) return state;
  const session = state.rootNodes.find(
    (n) => n.type === 'session' && n.id === params.sessionId,
  );
  if (!session) return state;
  // Mark the session node completed; preserve any in-flight child status
  // (the daemon already emitted turn_completed / tool_completed for those
  // before tearing the session down).
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, params.sessionId, (n) => ({
      ...n,
      status: 'completed' as const,
      endTime: Date.parse(params.timestamp),
      metadata: {
        ...(n.metadata ?? {}),
        endReason: params.reason,
      },
    })),
    activeNodeId: null,
  };
}

function addTurnNode(
  state: ExecutionTree,
  params: TurnStartedParams,
): ExecutionTree {
  // Turns nest under the deepest active step (when a plan is mid-execution)
  // or under the session otherwise. session_started may have been missed
  // (e.g. browser connected mid-prompt) — fall back to a root-level turn.
  const parent = findTurnParent(state, params.sessionId);

  const turn: ExecutionNode = {
    id: params.requestId,
    type: 'turn',
    status: 'running',
    label: `turn ${params.turnNumber}`,
    startTime: Date.parse(params.timestamp),
    children: [],
    metadata: { turnNumber: params.turnNumber },
  };

  let rootNodes: ExecutionNode[];
  if (parent) {
    rootNodes = appendChild(state.rootNodes, parent.id, turn);
  } else {
    // No session/step found — drop the turn at the root so it remains visible.
    rootNodes = [...state.rootNodes, turn];
  }

  return {
    ...state,
    rootNodes,
    activeNodeId: turn.id,
    // A new turn always starts a fresh ReAct loop — clear the thinking
    // and text anchors so the first event of this turn doesn't graft
    // itself onto the previous turn's last node.
    currentThinkingId: null,
    thinkingSealed: false,
    currentTextId: null,
    textIsOpen: false,
    stats: { ...state.stats, totalTurns: state.stats.totalTurns + 1 },
  };
}

function completeTurnNode(
  state: ExecutionTree,
  params: TurnCompletedParams,
): ExecutionTree {
  // Mark the turn AND every still-running thinking/text descendant as
  // completed. Tools manage their own status via stream.tool_completed,
  // but thinking and text are delta-only — there's no explicit "ended"
  // event for them, so without this sweep they'd stay in the 'running'
  // visual state (pulsing glow) forever even after the turn is over.
  // Capture stopReason on the turn's metadata so the renderer can
  // surface a badge for non-END_TURN endings (MAX_TOKENS, ERROR, …).
  // Older daemons that don't emit stopReason produce undefined, which
  // the renderer treats as "normal" — same visual as END_TURN.
  const rootNodes = mapNode(state.rootNodes, params.requestId, (n) => ({
    ...completeRunningDeltaDescendants(n),
    status: 'completed' as const,
    endTime: Date.parse(params.timestamp),
    duration: params.durationMs,
    metadata: {
      ...(n.metadata ?? {}),
      ...(params.stopReason !== undefined ? { stopReason: params.stopReason } : {}),
    },
  }));
  // Don't bubble activeNodeId up to the parent (session/step) when the
  // turn closes — that yanks the dashboard's auto-scroll back to the
  // session box, hiding the response the user just watched stream in.
  // Leaving activeNodeId on the last leaf makes the camera stay on the
  // response. The auto-scroll effect re-runs because layout.nodes
  // identity changed (turn status flipped to completed), but the
  // target is the leaf the user was already looking at, so the pan
  // is a no-op.
  return {
    ...state,
    rootNodes,
  };
}

/**
 * Returns {@code node} with every descendant of type {@code thinking} or
 * {@code text} that's still {@code running} flipped to {@code completed}.
 * Pure recursion; preserves all other fields. Used by
 * {@link completeTurnNode} so the turn's delta-stream children stop
 * pulsing the moment the turn closes.
 */
function completeRunningDeltaDescendants(node: ExecutionNode): ExecutionNode {
  if (node.children.length === 0) return node;
  const updated = node.children.map((c) => {
    const child = completeRunningDeltaDescendants(c);
    if ((child.type === 'thinking' || child.type === 'text') && child.status === 'running') {
      return { ...child, status: 'completed' as const };
    }
    return child;
  });
  return { ...node, children: updated };
}

function addToolNode(
  state: ExecutionTree,
  params: ToolUseParams,
): ExecutionTree {
  // Tools attach to the deepest causal node of the current iteration:
  //   1. The iteration's narration (text) when one exists — narration is
  //      the model verbalising its plan ("I'll call A and B"), and the
  //      tools that follow are the execution of that plan. Parent → child.
  //   2. Otherwise the iteration's thinking — when the model went straight
  //      from reasoning to acting with no narration, thinking is the cause.
  //   3. Otherwise a freshly-minted SYNTHETIC thinking under the running
  //      turn (see iteration-boundary block below). Dropping the tool as
  //      a direct child of the turn was the prior fallback, but it left
  //      the tool visually parallel with the next iteration's thinking
  //      node — readers (correctly) interpret that as "tool ran in
  //      parallel with thinking", which doesn't match the actual
  //      sequential ReAct flow. The synthetic thinking gives the tool a
  //      proper parent so the layout chains turn → thinking → tool →
  //      next-thinking → text horizontally.
  // Parallel tools from one LLM response don't get a thinking delta or
  // a text delta between them, so they share the same anchor — they
  // attach as siblings to whichever anchor was selected for the first
  // tool of the call.
  const turn = findNearestAncestor(
    state.rootNodes,
    state.activeNodeId,
    (n) => n.type === 'turn' && n.status === 'running',
  );

  // Iteration-boundary synthesis (mirrors appendTextToCurrentTurn):
  // when this tool_use is the FIRST event of a new iteration with no
  // narration open and no live thinking anchor, mint a synthetic
  // thinking node so the tool has a proper ReAct parent. Two trigger
  // shapes:
  //   1. textIsOpen=false + currentThinkingId=null — first event of
  //      the turn is a tool_use (extended thinking off, or model went
  //      straight to acting).
  //   2. textIsOpen=false + thinkingSealed=true — previous iteration
  //      ended via tool_use; this is a NEW iteration's tool.
  // Suppress the synthesis when there's a running sibling tool under
  // the current anchor — that signals parallel tools from the SAME LLM
  // call, which must keep sharing the existing anchor.
  let workingState = state;
  if (
    turn &&
    state.currentTextId === null &&
    (state.currentThinkingId === null || state.thinkingSealed)
  ) {
    const currentAnchor = state.currentThinkingId
      ? findNode(state.rootNodes, state.currentThinkingId)
      : null;
    const hasRunningSiblingTool = currentAnchor
      ? currentAnchor.children.some(
          (c) => c.type === 'tool' && c.status === 'running',
        )
      : false;
    if (!hasRunningSiblingTool) {
      workingState = mintIterationThinking(state, turn, '', 'completed').state;
    }
  }
  // Use workingState (= state if no synthesis) for the rest. Rebinding
  // keeps the existing logic readable; the original `state` is no
  // longer referenced.
  state = workingState;

  // Tool anchor preference: the active narration text (if one is open
  // OR was the most recent under current thinking) > thinking > turn.
  // currentTextId stays valid through parallel tool_use events so they
  // share the same anchor. textIsOpen=false (after a tool closed the
  // text) keeps the anchor for parallel-tool grouping but signals to
  // the next text delta that it's a NEW iteration.
  const anchorId =
    state.currentTextId ?? state.currentThinkingId ?? (turn ? turn.id : null);
  const narrationId = state.currentTextId;

  const tool: ExecutionNode = {
    id: params.id,
    type: 'tool',
    status: 'running',
    label: params.summary ? `${params.name} — ${params.summary}` : params.name,
    children: [],
    metadata: { tool: params.name, summary: params.summary },
  };

  let rootNodes: ExecutionNode[];
  if (anchorId) {
    // Parallel detection: a running sibling tool under the same anchor (be
    // that the thinking or the turn) means this is a parallel call from
    // the same LLM response. One-way flag on the turn for sidebar stats.
    const anchorPath = findPath(state.rootNodes, anchorId);
    const anchorNode = anchorPath ? anchorPath[anchorPath.length - 1]! : null;
    const hasRunningSibling = anchorNode
      ? anchorNode.children.some(
          (c) => c.type === 'tool' && c.status === 'running',
        )
      : false;
    rootNodes = mapNode(state.rootNodes, anchorId, (a) => ({
      ...a,
      children: [...a.children, tool],
    }));
    if (turn && (hasRunningSibling || turn.parallel)) {
      // Conditional spread because exactOptionalPropertyTypes forbids
      // assigning `undefined` to an optional property.
      rootNodes = mapNode(rootNodes, turn.id, (t) => ({ ...t, parallel: true }));
    }
  } else {
    rootNodes = [...state.rootNodes, tool];
  }

  // Mark the thinking AND any narration text as completed: once
  // tool_use starts, the LLM has stopped both reasoning and talking
  // for this iteration — both should stop pulsing immediately so the
  // visual state matches reality. Only flip 'running' → 'completed'
  // so a node that already failed/etc. isn't clobbered.
  if (state.currentThinkingId) {
    rootNodes = mapNode(rootNodes, state.currentThinkingId, (t) =>
      t.status === 'running' ? { ...t, status: 'completed' as const } : t,
    );
  }
  if (narrationId) {
    rootNodes = mapNode(rootNodes, narrationId, (t) =>
      t.status === 'running' ? { ...t, status: 'completed' as const } : t,
    );
  }

  let next: ExecutionTree = {
    ...state,
    rootNodes,
    activeNodeId: tool.id,
    // Seal both anchors: a tool_use means the model has stopped
    // thinking AND stopped talking; the next thinking OR text delta is
    // from a NEW LLM call (next ReAct iteration). Parallel tool_use
    // events that follow within the SAME call don't have a thinking
    // or text delta between them, so currentThinkingId / currentTextId
    // stay valid for parallel-tool grouping.
    thinkingSealed: true,
    textIsOpen: false,
    stats: { ...state.stats, totalTools: state.stats.totalTools + 1 },
  };
  // Drain any buffered permission.request that arrived BEFORE this
  // tool_use event (parallel virtual threads on the daemon dispatch
  // permission.request and stream.tool_use independently — wire order
  // is non-deterministic). The buffer is keyed by toolUseId; if our
  // new node matches, apply the awaiting marker now so the user gets
  // the "click ✓/✗" chip without delay.
  const buffered = next.pendingPermissionsByToolUseId[params.id];
  if (buffered) {
    const { [params.id]: _consumed, ...rest } = next.pendingPermissionsByToolUseId;
    void _consumed;
    next = applyPermissionAwaiting(
      { ...next, pendingPermissionsByToolUseId: rest },
      params.id,
      {
        tool: buffered.tool,
        description: buffered.description,
        requestId: buffered.requestId,
        toolUseId: params.id,
      },
      buffered.requestedAt,
    );
  }
  return next;
}

function completeToolNode(
  state: ExecutionTree,
  params: ToolCompletedParams,
): ExecutionTree {
  const node = findNode(state.rootNodes, params.id);
  if (!node) return state;

  const status: ExecutionNode['status'] = params.isError ? 'failed' : 'completed';
  const rootNodes = mapNode(state.rootNodes, params.id, (n) => {
    const error = params.error ?? n.error;
    // If the tool completes while still awaitingInput AND no local click
    // resolved it, the CLI must have answered the permission first
    // (first-response-wins via the daemon's permissionRegistry, #433).
    // Stamp resolvedBy='cli' for diagnostics + strip the panel-trigger
    // fields so the node stops looking "click to approve" in the tree.
    // Keeping awaitingInput here would leave a forever-clickable node
    // (the original click-to-open UX flowed via that flag); strip it
    // and the dashboard self-corrects to the daemon's verdict.
    const isExternalResolution =
      n.awaitingInput === true && (n.metadata?.['resolvedBy'] ?? null) === null;
    if (isExternalResolution) {
      const {
        awaitingInput: _ai,
        inputPrompt: _ip,
        permissionRequestId: _pid,
        ...rest
      } = n;
      void _ai; void _ip; void _pid;
      return {
        ...rest,
        status,
        duration: params.durationMs,
        ...(error !== undefined ? { error } : {}),
        metadata: {
          ...(n.metadata ?? {}),
          resolvedBy: 'cli',
          resolvedApproved: !params.isError,
        },
      };
    }
    return {
      ...n,
      status,
      duration: params.durationMs,
      ...(error !== undefined ? { error } : {}),
    };
  });

  // Move active back up to the parent turn so the next tool_use attaches there.
  const path = findPath(rootNodes, params.id) ?? [];
  const parent = path.length >= 2 ? path[path.length - 2] : null;

  return {
    ...state,
    rootNodes,
    activeNodeId: parent ? parent.id : state.activeNodeId,
    stats: {
      ...state.stats,
      completedTools: state.stats.completedTools + (params.isError ? 0 : 1),
      failedTools: state.stats.failedTools + (params.isError ? 1 : 0),
    },
  };
}

/**
 * Truncates text for use as a node label. Tier-1 nodes are 180 px wide
 * and the renderer truncates to ~24 chars; we cap a bit shorter here
 * so the live preview reads cleanly while the text streams. Strips
 * leading whitespace because the model often opens a paragraph with a
 * newline and an indent that would otherwise dominate the preview.
 */
function previewLabel(text: string, max = 22): string {
  const trimmed = text.replace(/^\s+/, '');
  if (trimmed.length <= max) return trimmed;
  return `${trimmed.slice(0, max - 1)}…`;
}

function appendTextToCurrentTurn(
  state: ExecutionTree,
  params: TextDeltaParams,
): ExecutionTree {
  // Text in a Claude streaming response is per-LLM-call. Two anchors
  // separate "extend the live text" from "start a new iteration's
  // text": currentTextId tracks the live node; textIsOpen=false (set
  // by tool_use) signals that the text was sealed and the next delta
  // belongs to a NEW iteration. Without this flag, an iteration that
  // skips its thinking block (model went straight from tool result to
  // final response) would silently merge into the previous iter's
  // text node, because both ids would key on the same currentThinkingId.
  const turn = findNearestAncestor(
    state.rootNodes,
    state.activeNodeId,
    (n) => n.type === 'turn' && n.status === 'running',
  );
  if (!turn) return state;

  // If we're starting a new iteration's text without a fresh
  // stream.thinking event, mint a SYNTHETIC thinking node to anchor
  // it. Two cases trigger this:
  //   1. textIsOpen=false + thinkingSealed=true: previous iteration
  //      closed by a tool_use, next call started with text directly.
  //   2. textIsOpen=false + currentThinkingId=null: this is the very
  //      first event of the turn AND it's a text (extended thinking
  //      off, model went straight to text). Without the synthetic
  //      thinking the text would land as a turn-direct child and
  //      addReActFlowEdges (which only iterates thinking siblings)
  //      would orphan it from the ReAct chain.
  //
  // The synthetic thinking is created status=completed — the model
  // already finished thinking by the time we infer the boundary from
  // a text delta — and gets the same shape as a real thinking node
  // so the layout chains identically.
  let workingState = state;
  if (
    !state.textIsOpen &&
    (state.thinkingSealed || state.currentThinkingId === null)
  ) {
    workingState = mintIterationThinking(state, turn, '', 'completed').state;
  }

  let textId: string;
  let isNewNode: boolean;
  let nextSyntheticId = workingState.nextSyntheticId;
  if (workingState.currentTextId && workingState.textIsOpen) {
    textId = workingState.currentTextId;
    isNewNode = false;
  } else {
    // New iteration: mint a unique id keyed on (anchor, counter).
    // The counter (nextSyntheticId) ensures uniqueness even when an
    // iteration's text follows a tool_use without a fresh thinking
    // delta — both ids would key on the same currentThinkingId
    // otherwise and silently collide.
    const counter = nextSyntheticId;
    nextSyntheticId += 1;
    textId =
      workingState.currentThinkingId !== null
        ? `${workingState.currentThinkingId}:text:${counter}`
        : `${turn.id}:text:${counter}`;
    isNewNode = true;
  }

  const existing = !isNewNode ? findNode(workingState.rootNodes, textId) : null;
  const newText = (existing?.text ?? '') + params.delta;
  let rootNodes: ExecutionNode[];
  if (existing) {
    rootNodes = mapNode(workingState.rootNodes, textId, (t) => ({
      ...t,
      text: newText,
      label: previewLabel(newText),
    }));
  } else {
    const anchorId = workingState.currentThinkingId ?? turn.id;
    const textNode: ExecutionNode = {
      id: textId,
      type: 'text',
      status: 'running',
      label: previewLabel(newText),
      children: [],
      text: newText,
    };
    rootNodes = appendChild(workingState.rootNodes, anchorId, textNode);
  }

  // Mark the thinking anchor as completed: text means the LLM has
  // stopped thinking and is now talking.
  if (workingState.currentThinkingId) {
    rootNodes = mapNode(rootNodes, workingState.currentThinkingId, (t) =>
      t.status === 'running' ? { ...t, status: 'completed' as const } : t,
    );
  }

  // Move auto-scroll focus onto the streaming text. Subsequent deltas
  // keep the same id (textIsOpen stays true), so the camera sits on
  // this bubble until tool_use closes it or the turn ends. Spread
  // workingState (not state) to preserve any synthetic-thinking
  // mutations from the iteration-boundary helper above.
  return {
    ...workingState,
    rootNodes,
    activeNodeId: textId,
    currentTextId: textId,
    textIsOpen: true,
    thinkingSealed: true,
    ...(isNewNode ? { nextSyntheticId } : {}),
  };
}

/**
 * Mints a new thinking node under {@code turn} and returns the updated
 * tree state. Encapsulates the "iteration boundary" reconciliation
 * (provisionally complete previous iteration's running work) plus the
 * iteration-anchor reset (clear currentTextId/textIsOpen). Used by both
 * {@link appendThinkingToCurrentTurn} (real thinking deltas) and
 * {@link appendTextToCurrentTurn} (synthetic thinking when text starts a
 * new iteration without a preceding stream.thinking event).
 *
 * @param initialDelta first thinking delta — for synthetic insertions
 *   pass an empty string
 * @param initialStatus 'running' for real thinking, 'completed' for
 *   synthetic placeholders (the "model didn't think" case is already
 *   over by the time we infer the iteration boundary from a text delta)
 */
function mintIterationThinking(
  state: ExecutionTree,
  turn: ExecutionNode,
  initialDelta: string,
  initialStatus: ExecutionStatus,
): { state: ExecutionTree; thinkingId: string } {
  // Reconcile previous iteration: provisionally complete any
  // still-running tools/text under the prior thinking so they stop
  // pulsing as soon as we know the next iteration has started. Real
  // tool_completed events still apply normally when they arrive.
  let preparedRootNodes = state.rootNodes;
  if (state.currentThinkingId) {
    preparedRootNodes = mapNode(state.rootNodes, state.currentThinkingId, (n) =>
      provisionallyCompleteRunningWork(n),
    );
  }

  const existingThinkingCount = countDescendantsOfType(turn, 'thinking');
  const id =
    existingThinkingCount === 0
      ? thinkingNodeId(turn.id)
      : `${thinkingNodeId(turn.id)}:${existingThinkingCount}`;
  const thinkingNode: ExecutionNode = {
    id,
    type: 'thinking',
    status: initialStatus,
    label: 'thinking',
    children: [],
    text: initialDelta,
  };
  const newState: ExecutionTree = {
    ...state,
    rootNodes: appendChild(preparedRootNodes, turn.id, thinkingNode),
    // Move auto-scroll focus to the new thinking node so the camera
    // pans to it as it arrives. Without this, a new ReAct iteration's
    // thinking lands off the right edge of the viewport (downstream of
    // the just-completed tool) and the user sees no movement until a
    // text delta later flips activeNodeId — at which point the canvas
    // jumps two steps ahead. With the focus move + the SVG transition
    // on style.transform, every new node slides smoothly into view.
    activeNodeId: id,
    currentThinkingId: id,
    thinkingSealed: false,
    // New iteration: forget the previous iteration's text anchors so
    // tools/text in this iteration attach to the new thinking, not the
    // old text node.
    currentTextId: null,
    textIsOpen: false,
  };
  return { state: newState, thinkingId: id };
}

function appendThinkingToCurrentTurn(
  state: ExecutionTree,
  params: ThinkingDeltaParams,
): ExecutionTree {
  // Builds a {@code thinking}-typed node under the running turn. The
  // reducer used to drop these — meaning a turn that only thought (no
  // tools, no text yet) showed up as an empty parent. A turn can have
  // MULTIPLE thinking nodes, one per ReAct iteration — each iteration is a
  // separate LLM call, and the boundary is detected via {@link
  // ExecutionTree#thinkingSealed}: a tool_use or text delta seals the
  // current thinking node, so the next thinking delta starts a fresh one.
  // Parallel tool_use events from a single LLM response don't seal the
  // anchor between themselves (no thinking delta arrives between them), so
  // they correctly attach to the same parent.
  const turn = findNearestAncestor(
    state.rootNodes,
    state.activeNodeId,
    (n) => n.type === 'turn' && n.status === 'running',
  );
  if (!turn) return state;

  // Same iteration: append the delta to the existing thinking node.
  if (state.currentThinkingId && !state.thinkingSealed) {
    return {
      ...state,
      rootNodes: mapNode(state.rootNodes, state.currentThinkingId, (t) => ({
        ...t,
        text: (t.text ?? '') + params.delta,
      })),
      // Keep auto-scroll focus on the streaming thinking node so a
      // long thought doesn't drift off-screen as content grows.
      activeNodeId: state.currentThinkingId,
    };
  }

  // New iteration boundary — delegate to the shared mint helper which
  // handles previous-iteration reconciliation (provisional completion
  // of running tools/text), id minting, and anchor reset.
  return mintIterationThinking(state, turn, params.delta, 'running').state;
}

/**
 * Returns {@code node} with every still-running {@code tool} or
 * {@code text} descendant flipped to {@code completed}. Used at
 * iteration boundaries to absorb the timing slop between a tool
 * finishing on the daemon side and its {@code tool_completed} event
 * arriving on the wire — the next iteration's events frequently
 * overtake the completion broadcast, leaving previous-iteration tools
 * stuck pulsing in the dashboard. The real tool_completed event is
 * still applied normally when it arrives; this just removes the
 * visual ambiguity in the gap.
 */
function provisionallyCompleteRunningWork(node: ExecutionNode): ExecutionNode {
  if (node.children.length === 0) return node;
  const updated = node.children.map((c) => {
    const child = provisionallyCompleteRunningWork(c);
    if (
      (child.type === 'tool' || child.type === 'text') &&
      child.status === 'running'
    ) {
      return { ...child, status: 'completed' as const };
    }
    return child;
  });
  return { ...node, children: updated };
}

/**
 * Counts every descendant of {@code root} (any depth) whose type matches.
 * Used to mint stable unique ids for repeated-per-turn synthetic nodes
 * (e.g. multiple thinking blocks across ReAct iterations).
 */
function countDescendantsOfType(
  root: ExecutionNode,
  type: ExecutionNode['type'],
): number {
  let count = 0;
  const stack: ExecutionNode[] = [...root.children];
  while (stack.length > 0) {
    const n = stack.pop()!;
    if (n.type === type) count += 1;
    if (n.children.length > 0) stack.push(...n.children);
  }
  return count;
}

function addPlanSkeleton(
  state: ExecutionTree,
  params: PlanCreatedParams,
): ExecutionTree {
  // Plan attaches to the nearest running turn (its conceptual owner). Steps
  // are pre-created as pending children so the dashboard can show the full
  // skeleton before any step runs — the headline visualisation feature.
  const owner =
    findNearestAncestor(
      state.rootNodes,
      state.activeNodeId,
      (n) => n.type === 'turn' && n.status === 'running',
    ) ??
    findNearestAncestor(
      state.rootNodes,
      state.activeNodeId,
      (n) => n.type === 'session',
    );

  const stepChildren: ExecutionNode[] = params.steps.map((s) => ({
    id: stepNodeId(params.planId, s.index),
    type: 'step',
    status: 'pending',
    label: s.name,
    children: [],
    metadata: { stepIndex: s.index, description: s.description },
  }));
  const plan: ExecutionNode = {
    id: params.planId,
    type: 'plan',
    status: 'running',
    label: `plan: ${params.goal}`,
    children: stepChildren,
    metadata: {
      planId: params.planId,
      stepCount: params.stepCount,
      resumed: params.resumed ?? false,
      ...(params.resumedFromStep !== undefined
        ? { resumedFromStep: params.resumedFromStep }
        : {}),
    },
  };

  if (owner) {
    return {
      ...state,
      rootNodes: appendChild(state.rootNodes, owner.id, plan),
    };
  }
  return { ...state, rootNodes: [...state.rootNodes, plan] };
}

function activateStep(
  state: ExecutionTree,
  params: PlanStepStartedParams,
): ExecutionTree {
  const composedId = stepNodeId(params.planId, params.stepIndex);
  const existing = findNode(state.rootNodes, composedId);

  // Skeleton-update path: the only state that means "this slot is a fresh
  // pre-created skeleton waiting to be activated" is 'pending'. Everything
  // else — running (duplicate event), completed/failed (replan after the
  // step already finished), cancelled (replan after pending), paused
  // (mid-permission) — is a tombstone whose history must be preserved. Mint
  // a synthetic id for the new step instead of overwriting.
  if (existing && existing.status === 'pending') {
    return {
      ...state,
      rootNodes: mapNode(state.rootNodes, composedId, (n) => ({
        ...n,
        status: 'running',
        label: params.stepName,
      })),
      activeNodeId: composedId,
    };
  }

  // From here, we either have no skeleton yet (out-of-order arrival) or we
  // hit a tombstone of any non-pending status left behind by replan. In both
  // cases we want to insert a NEW running step — but only if the plan itself
  // exists. If not, decline to move focus rather than dangle activeNodeId at
  // a node that no later handler can find.
  const plan = findNode(state.rootNodes, params.planId);
  if (!plan) {
    return state;
  }

  // Any existing tombstone (cancelled / completed / failed / running / paused)
  // must keep its history — a naive resurrection at the colliding composed id
  // would erase replan history or overwrite a successfully completed step's
  // record. Mint a synthetic id ({composedId}:r{n}) so the tombstone and the
  // new step coexist as siblings under the plan.
  const isReplanResurrection = existing != null;
  const newStepId = isReplanResurrection
    ? `${composedId}:r${state.nextSyntheticId}`
    : composedId;
  const newCounter = isReplanResurrection
    ? state.nextSyntheticId + 1
    : state.nextSyntheticId;

  const rootNodes = mapNode(state.rootNodes, params.planId, (p) => ({
    ...p,
    children: [
      ...p.children,
      {
        id: newStepId,
        type: 'step',
        status: 'running',
        label: params.stepName,
        children: [],
        metadata: {
          stepIndex: params.stepIndex,
          totalSteps: params.totalSteps,
          createdByReplan: isReplanResurrection,
        },
      },
    ],
  }));
  return {
    ...state,
    rootNodes,
    activeNodeId: newStepId,
    nextSyntheticId: newCounter,
  };
}

function completeStep(
  state: ExecutionTree,
  params: PlanStepCompletedParams,
): ExecutionTree {
  const composedId = stepNodeId(params.planId, params.stepIndex);
  // Resolve the step we should complete. Two paths:
  //   1. Composed id matches a still-running pre-created skeleton step.
  //   2. Plan has a running step at a synthetic id (replan path) — find it
  //      by scanning the plan's children rather than relying on activeNodeId,
  //      because the active node has typically moved to a child tool/text by
  //      the time plan_step_completed arrives.
  const composedExisting = findNode(state.rootNodes, composedId);
  const skeletonHit =
    composedExisting && composedExisting.status === 'running'
      ? composedId
      : null;
  const plan = findNode(state.rootNodes, params.planId);
  const replanRunningStep = plan?.children.find(
    (c) => c.type === 'step' && c.status === 'running',
  );
  const stepId = skeletonHit ?? replanRunningStep?.id ?? null;

  if (!stepId) {
    // No matching step (e.g. plan_step_completed before plan_created). Decline
    // to move focus — we can't honour the event meaningfully.
    return state;
  }

  const rootNodes = mapNode(state.rootNodes, stepId, (n) => ({
    ...n,
    status: params.success ? 'completed' : 'failed',
    duration: params.durationMs,
  }));
  // Step done → next pending sibling inherits focus, else the plan, else
  // leave focus alone (plan was missing too).
  const planAfter = findNode(rootNodes, params.planId);
  if (!planAfter) {
    return { ...state, rootNodes };
  }
  const nextPending = planAfter.children.find(
    (c) => c.type === 'step' && c.status === 'pending',
  );
  return {
    ...state,
    rootNodes,
    activeNodeId: nextPending ? nextPending.id : params.planId,
  };
}

function markStepFallback(
  state: ExecutionTree,
  params: PlanStepFallbackParams,
): ExecutionTree {
  const stepId = stepNodeId(params.planId, params.stepIndex);
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, stepId, (n) => ({
      ...n,
      metadata: {
        ...(n.metadata ?? {}),
        fallback: {
          approach: params.fallbackApproach,
          attempt: params.attempt,
        },
      },
    })),
  };
}

function replacePlanSteps(
  state: ExecutionTree,
  params: PlanReplannedParams,
): ExecutionTree {
  // The daemon's PlanReplanned only carries newStepCount + rationale, not the
  // full new step list (#439). Three things happen on replan (#458):
  //   1. Cancel non-completed steps — preserves history of what was dropped
  //   2. Insert a synthetic 'replan' marker node after the cancelled steps —
  //      gives the replan event itself an addressable id, so it can be
  //      clicked, hovered, diffed across runs, and (later) used as a
  //      step boundary for the agent debugger
  //   3. Stamp the plan with replan metadata so a chip on the plan node
  //      can show "replan ×N" without scrolling to find a marker
  // The marker's status is 'completed' because the replan event itself is
  // instantaneous — the surrounding step nodes carry the actual progress.
  // Subsequent plan_step_started events lazy-append new steps via
  // activateStep, so they naturally land AFTER the replan marker, giving
  // the timeline: [cancelled steps] → [replan marker] → [new steps].
  const cancelledStepCount = countCancellableSteps(state.rootNodes, params.planId);
  const replanMarker: ExecutionNode = {
    id: `${params.planId}::replan-${params.replanAttempt}`,
    type: 'replan',
    status: 'completed',
    label: `Replan #${params.replanAttempt}`,
    children: [],
    metadata: {
      rationale: params.rationale,
      replanAttempt: params.replanAttempt,
      cancelledStepCount,
      newStepCount: params.newStepCount,
    },
  };
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, params.planId, (plan) => ({
      ...plan,
      children: [
        ...plan.children.map((c) =>
          c.type === 'step' && c.status !== 'completed'
            ? { ...c, status: 'cancelled' as const }
            : c,
        ),
        replanMarker,
      ],
      metadata: {
        ...(plan.metadata ?? {}),
        replanAttempt: params.replanAttempt,
        replanRationale: params.rationale,
        newStepCount: params.newStepCount,
      },
    })),
  };
}

/**
 * Counts how many step children of {@code planId} would be NEWLY
 * cancelled by this replan event. Used by the synthetic replan marker's
 * metadata so the renderer can surface "this revision dropped N steps
 * and added M".
 *
 * <p>Crucially excludes both {@code 'completed'} (preserved history)
 * AND {@code 'cancelled'} (tombstones from earlier replans). Without
 * the cancelled-exclusion the second replan's marker would over-count:
 * if replan #1 dropped 3 steps and replan #2 newly drops 1, replan #2's
 * marker would say "dropped 4" because the 3 already-cancelled
 * tombstones still live in {@code plan.children} and would be re-counted.
 *
 * <p>Pure function; returns 0 if the plan can't be found.
 */
function countCancellableSteps(
  rootNodes: ExecutionNode[],
  planId: string,
): number {
  const plan = findNode(rootNodes, planId);
  if (!plan) return 0;
  return plan.children.filter(
    (c) => c.type === 'step'
      && c.status !== 'completed'
      && c.status !== 'cancelled',
  ).length;
}

function completePlan(
  state: ExecutionTree,
  params: PlanCompletedParams,
): ExecutionTree {
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, params.planId, (n) => ({
      ...n,
      status: params.success ? 'completed' : 'failed',
      duration: params.totalDurationMs,
      metadata: {
        ...(n.metadata ?? {}),
        stepsCompleted: params.stepsCompleted,
        totalSteps: params.totalSteps,
      },
    })),
  };
}

function failPlan(
  state: ExecutionTree,
  params: PlanEscalatedParams,
): ExecutionTree {
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, params.planId, (n) => ({
      ...n,
      status: 'failed',
      error: params.reason,
    })),
  };
}

function addSubAgentNode(
  state: ExecutionTree,
  params: SubAgentStartParams,
): ExecutionTree {
  const turn = findNearestAncestor(
    state.rootNodes,
    state.activeNodeId,
    (n) => n.type === 'turn' && n.status === 'running',
  );
  // Sub-agent ids in the daemon are not unique across the same agentType
  // running twice in one turn (#439). Mint a synthetic id from the per-tree
  // monotonic counter so two subagent.start events back-to-back with the
  // same agentType cannot collide. The counter lives on state (not a module
  // variable) so the reducer stays pure and a snapshot replay produces the
  // same tree on every machine.
  const syntheticId = state.nextSyntheticId;
  const id = `subagent:${params.agentType}:${syntheticId}`;
  const node: ExecutionNode = {
    id,
    type: 'subagent',
    status: 'running',
    label: `subagent: ${params.agentType}`,
    children: [],
    metadata: { agentType: params.agentType, prompt: params.prompt },
  };
  const baseRootNodes = turn
    ? appendChild(state.rootNodes, turn.id, node)
    : [...state.rootNodes, node];
  return {
    ...state,
    rootNodes: baseRootNodes,
    activeNodeId: id,
    nextSyntheticId: syntheticId + 1,
  };
}

/**
 * Pattern that matches synthetic subagent ids minted by {@link addSubAgentNode},
 * format {@code subagent:{agentType}:{counter}}. Capture group 1 is the
 * monotonic counter that lets us pick "most recently started" deterministically
 * instead of relying on DFS traversal order.
 */
const SUBAGENT_ID_PATTERN = /^subagent:.+:(\d+)$/;

function completeSubAgentNode(
  state: ExecutionTree,
  params: SubAgentEndParams,
): ExecutionTree {
  // Daemon doesn't carry a unique id on subagent.end (#439), so we resolve
  // among running subagents matching the agentType. With two same-type
  // subagents alive in different branches, DFS order is whatever the tree
  // shape happens to be; using the highest synthetic counter gives
  // deterministic LIFO (last started, first ended), which is the
  // overwhelmingly common pattern. Snapshot-replay nodes that lack the
  // synthetic suffix fall back to the last DFS match.
  let target: ExecutionNode | null = null;
  let highestCounter = -1;
  const visit = (nodes: readonly ExecutionNode[]): void => {
    for (const n of nodes) {
      if (
        n.type === 'subagent' &&
        n.status === 'running' &&
        n.metadata?.['agentType'] === params.agentType
      ) {
        const m = SUBAGENT_ID_PATTERN.exec(n.id);
        if (m && m[1]) {
          const counter = Number(m[1]);
          if (counter > highestCounter) {
            highestCounter = counter;
            target = n;
          }
        } else if (highestCounter < 0) {
          // No synthetic suffix (e.g. snapshot-loaded node). Tracking here
          // only kicks in when no synthetic-id match has been found yet.
          target = n;
        }
      }
      visit(n.children);
    }
  };
  visit(state.rootNodes);
  if (!target) return state;
  const targetId = (target as ExecutionNode).id;
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, targetId, (n) => ({
      ...n,
      status: 'completed',
    })),
  };
}

/**
 * Marks {@code targetNodeId} as paused awaiting a permission decision.
 * Pure helper used by both {@link pauseForPermission} (when the target
 * node already exists) and {@link addToolNode} (when a buffered
 * permission for the new node was waiting on its arrival).
 *
 * <p>Also sets {@code activeNodeId} to the awaiting node so the
 * camera's auto-scroll effect pans the node into view if it's
 * outside the comfort zone — a permission-awaiting node off the
 * right edge would otherwise be invisible (no chip on screen) and
 * the user couldn't approve it without scrolling. Combined with
 * the comfort-zone guard in ExecutionTree's auto-scroll, this only
 * actually moves the camera when the awaiting node is past the edge.
 */
function applyPermissionAwaiting(
  state: ExecutionTree,
  targetNodeId: string,
  params: PermissionRequestParams,
  requestedAt: number,
): ExecutionTree {
  return {
    ...state,
    activeNodeId: targetNodeId,
    rootNodes: mapNode(state.rootNodes, targetNodeId, (n) => ({
      ...n,
      status: 'paused',
      awaitingInput: true,
      inputPrompt: params.description,
      permissionRequestId: params.requestId,
      metadata: {
        ...(n.metadata ?? {}),
        permissionTool: params.tool,
        permissionRequestedAt: requestedAt,
      },
    })),
  };
}

function pauseForPermission(
  state: ExecutionTree,
  params: PermissionRequestParams,
  receivedAt: string,
): ExecutionTree {
  // The daemon pauses execution waiting for a permission.response. We mark
  // the active leaf as paused + awaitingInput so the renderer can surface
  // the prompt right where the agent stopped. Stamp requestedAt from the
  // envelope's receivedAt (set by the bridge when the daemon emitted the
  // event) so the PermissionPanel's countdown is correct on snapshot
  // replay too — using Date.now() here would re-stamp every replay with
  // the current wall clock, making aged requests look fresh and breaking
  // the deadline math. Server side caps at 120 s — see
  // CancelAwareStreamContext.PERMISSION_RESPONSE_TIMEOUT_MS.
  //
  const requestedAtRaw = Date.parse(receivedAt);
  const requestedAt = Number.isFinite(requestedAtRaw) ? requestedAtRaw : Date.now();

  // Target resolution, in order of preference:
  //   1. toolUseId names a node already in the tree → mark that node.
  //      This is the per-tool-node path that disambiguates parallel
  //      permissions (#437).
  //   2. toolUseId is provided but its node hasn't arrived yet (race:
  //      parallel tool execution dispatches permission.request before
  //      the matching stream.tool_use lands on the wire). BUFFER the
  //      request keyed by toolUseId; addToolNode drains the buffer
  //      when the matching node is added.
  //   3. No toolUseId at all (older daemons predating the toolUseId
  //      emission). Fall back to activeNodeId — same legacy
  //      collapse-onto-last behaviour as before, kept for backward
  //      compat with daemons that haven't been rebuilt.
  if (params.toolUseId) {
    if (findNode(state.rootNodes, params.toolUseId)) {
      return applyPermissionAwaiting(state, params.toolUseId, params, requestedAt);
    }
    return {
      ...state,
      pendingPermissionsByToolUseId: {
        ...state.pendingPermissionsByToolUseId,
        [params.toolUseId]: {
          tool: params.tool,
          description: params.description,
          requestId: params.requestId,
          requestedAt,
        },
      },
    };
  }
  if (!state.activeNodeId) return state;
  return applyPermissionAwaiting(state, state.activeNodeId, params, requestedAt);
}

/**
 * Locally apply a user's Approve / Deny click to the paused node and clear
 * its awaitingInput flag. The browser still posts {@code permission.response}
 * over the WS for the daemon to act on — this reducer step just keeps the
 * UI in sync without waiting for a daemon-side reflection (the daemon
 * never echoes the response, it just resumes execution and emits
 * stream.tool_completed when the tool finishes).
 *
 * Status semantic mirrors the issue spec:
 *   - approved → 'running' (the tool is now executing on the daemon)
 *   - denied   → 'cancelled' (tool returns "Permission denied" and the
 *     model continues from the failure)
 *
 * Tagging metadata.resolvedBy = 'browser' lets a future "approved via X"
 * banner in the panel distinguish the responder. Idempotent: if no node
 * is found awaiting this requestId, the state is returned unchanged
 * (lets duplicate clicks no-op cleanly).
 */
/**
 * Tears down the permission panel for {@code requestId} by stripping the
 * panel-trigger fields ({@code awaitingInput}, {@code inputPrompt},
 * {@code permissionRequestId}) from whatever node carries them. Used by
 * the panel's dismiss timer after a CLI-resolved request has shown its
 * "Approved/Denied via CLI" state long enough to register on the eye.
 * Idempotent — a no-op when the request is no longer pending.
 */
export function dismissPermissionPanel(
  state: ExecutionTree,
  requestId: string,
): ExecutionTree {
  let target: ExecutionNode | null = null;
  const visit = (nodes: readonly ExecutionNode[]): void => {
    for (const n of nodes) {
      if (n.permissionRequestId === requestId && target === null) {
        target = n;
      }
      if (n.children.length > 0) visit(n.children);
    }
  };
  visit(state.rootNodes);
  if (!target) return state;
  const targetNode: ExecutionNode = target;
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, targetNode.id, (n) => {
      const {
        awaitingInput: _ai,
        inputPrompt: _ip,
        permissionRequestId: _pid,
        ...rest
      } = n;
      void _ai; void _ip; void _pid;
      return rest;
    }),
  };
}

export function resolvePermissionLocally(
  state: ExecutionTree,
  requestId: string,
  approved: boolean,
  resolvedBy: 'browser' | 'cli' = 'browser',
): ExecutionTree {
  let target: ExecutionNode | null = null;
  const visit = (nodes: readonly ExecutionNode[]): void => {
    for (const n of nodes) {
      if (
        n.awaitingInput === true &&
        n.permissionRequestId === requestId &&
        target === null
      ) {
        target = n;
      }
      if (n.children.length > 0) visit(n.children);
    }
  };
  visit(state.rootNodes);
  if (!target) return state;

  const targetNode: ExecutionNode = target;

  // Race guard: if the daemon already echoed tool_completed (CLI won the
  // race) the reducer's completeToolNode stamped resolvedBy='cli' and
  // moved the node to a terminal status, but kept awaitingInput=true so
  // the panel can briefly show "Approved/Denied via CLI". A tardy click
  // from the user must not overwrite that resolution: reverting status
  // from 'completed'/'failed' back to 'running' would resurrect a node
  // the daemon already finished, and stamping resolvedBy='browser' would
  // mislabel who actually resolved it. Bail to a panel-dismiss-only
  // path so the UI clears without corrupting state.
  if (
    targetNode.metadata?.['resolvedBy'] === 'cli' ||
    (targetNode.status !== 'paused' && resolvedBy === 'browser')
  ) {
    return dismissPermissionPanel(state, requestId);
  }

  const nextStatus: ExecutionStatus = approved ? 'running' : 'cancelled';
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, targetNode.id, (n) => {
      // Strip awaitingInput / inputPrompt / permissionRequestId from the
      // node so the panel unmounts. Drop them with destructuring rather
      // than setting `undefined` (exactOptionalPropertyTypes forbids it).
      const {
        awaitingInput: _ai,
        inputPrompt: _ip,
        permissionRequestId: _pid,
        ...rest
      } = n;
      void _ai; void _ip; void _pid;
      return {
        ...rest,
        status: nextStatus,
        metadata: {
          ...(n.metadata ?? {}),
          resolvedBy,
          resolvedApproved: approved,
        },
      };
    }),
  };
}

function updateUsageStats(
  state: ExecutionTree,
  params: UsageParams,
): ExecutionTree {
  return {
    ...state,
    stats: {
      ...state.stats,
      // totalInputTokens / totalOutputTokens are cumulative on the daemon
      // side — mirror the latest snapshot rather than summing locally.
      inputTokens: params.totalInputTokens,
      outputTokens: params.totalOutputTokens,
    },
  };
}

function addCompactionMarker(
  state: ExecutionTree,
  params: CompactionParams,
): ExecutionTree {
  // Surface a compaction event on the active turn's metadata so the renderer
  // can draw a small marker. No new node — compaction is metadata, not a
  // first-class tree node.
  const turn = findNearestAncestor(
    state.rootNodes,
    state.activeNodeId,
    (n) => n.type === 'turn',
  );
  if (!turn) return state;
  return {
    ...state,
    rootNodes: mapNode(state.rootNodes, turn.id, (t) => {
      const prior = (t.metadata?.['compactions'] as unknown[]) ?? [];
      return {
        ...t,
        metadata: {
          ...(t.metadata ?? {}),
          compactions: [
            ...prior,
            {
              originalTokens: params.originalTokens,
              compactedTokens: params.compactedTokens,
              phase: params.phase,
            },
          ],
        },
      };
    }),
  };
}

// ---------------------------------------------------------------------------
// Main reducer
// ---------------------------------------------------------------------------

/**
 * Reduces a daemon event envelope into a new ExecutionTree.
 *
 * Idempotent against snapshot replay: events with {@code eventId <= state.lastEventId}
 * are dropped, mirroring the dedup rule from #439's events.ts. Unknown event
 * methods (e.g. future Tier 3 swarm events) are ignored.
 */
export function executionTreeReducer(
  state: ExecutionTree,
  envelope: Envelope,
): ExecutionTree {
  // Snapshot/reconnect dedup: skip events the browser already saw.
  if (envelope.eventId > 0 && envelope.eventId <= state.lastEventId) {
    return state;
  }

  let next: ExecutionTree = state;
  const event = envelope.event;
  switch (event.method) {
    case 'stream.session_started':
      next = addSessionNode(state, event.params);
      break;
    case 'stream.session_ended':
      next = closeSessionNode(state, event.params);
      break;
    case 'stream.turn_started':
      next = addTurnNode(state, event.params);
      break;
    case 'stream.turn_completed':
      next = completeTurnNode(state, event.params);
      break;
    case 'stream.tool_use':
      next = addToolNode(state, event.params);
      break;
    case 'stream.tool_completed':
      next = completeToolNode(state, event.params);
      break;
    case 'stream.text':
      next = appendTextToCurrentTurn(state, event.params);
      break;
    case 'stream.thinking':
      next = appendThinkingToCurrentTurn(state, event.params);
      break;
    case 'stream.plan_created':
      next = addPlanSkeleton(state, event.params);
      break;
    case 'stream.plan_step_started':
      next = activateStep(state, event.params);
      break;
    case 'stream.plan_step_completed':
      next = completeStep(state, event.params);
      break;
    case 'stream.plan_step_fallback':
      next = markStepFallback(state, event.params);
      break;
    case 'stream.plan_replanned':
      next = replacePlanSteps(state, event.params);
      break;
    case 'stream.plan_completed':
      next = completePlan(state, event.params);
      break;
    case 'stream.plan_escalated':
      next = failPlan(state, event.params);
      break;
    case 'stream.subagent.start':
      next = addSubAgentNode(state, event.params);
      break;
    case 'stream.subagent.end':
      next = completeSubAgentNode(state, event.params);
      break;
    case 'permission.request':
      next = pauseForPermission(state, event.params, envelope.receivedAt);
      break;
    case 'stream.usage':
      next = updateUsageStats(state, event.params);
      break;
    case 'stream.compaction':
      next = addCompactionMarker(state, event.params);
      break;
    default:
      // Unknown / forward-compat method (Tier 2/3 swarm, custom namespaces).
      // Intentionally ignored — schema reserves these for future expansion.
      break;
  }

  // Watermark advances even on no-op events so reconnect dedup stays accurate.
  if (envelope.eventId > next.lastEventId) {
    return { ...next, lastEventId: envelope.eventId };
  }
  return next;
}
